version: "3.9"
services:
  app:
    build: ./
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:test_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 49918003
      SPRING_JPA_HIBERNATE_DDL_AUTO: update